title: mtu.present
logo:
description: Beamer themes for Michigan Technological University branded presentations.
show_downloads: true
github:
    zip_url: https://github.com/JasonHiebel/mtu.present/archive/master.zip
    tar_url: https://github.com/JasonHiebel/mtu.present/archive/master.tar.gz
    repository_url: https://github.com/JasonHiebel/mtu.present
google_analytics:
gems:
- jekyll-seo-tag
